apiVersion: v1
kind: Pod
metadata:
   name: springboot-pod
   labels:
     app: springboot-pod
spec:
   containers:
   - name: springboot-container
     image: shivtejopsverse/springboot:run3-amd64
     ports:
     - containerPort: 8080
