apiVersion: v1
kind: Pod
metadata:
   name: springboot-pod
spec:
   containers:
   - name: springboot-container
     image: shivtejopsverse/springboot:run2-amd64
     ports:
     - containerPort: 8080